### ISSUE TITLE
Javadoc comments with carriage returns

### ISSUE THREAD

**Issue by mattadamson** [johncarl81/exportdoclet#2]
Hi

Currently when we add javadoc comments e.g. to class definitions the eclipse IDE formatting settings will wrap with carriage returns to ensure the comment stays in view in the editor.  This makes perfect sense however in ascii doctor we often don't want to do this i.e. we use soft wrapping. How do others handle this? Is there a configuration option we could enable to take carriage return line feeds within eclipse and remove although this would be difficult as some CRLF characters maybe required for paragraph separation.  

Thanks

Matt

**Comment by johncarl81** [comment]
Can you give an example?
